{{- if .Values.discovery.enabled }}
{{- $fullname := include "common.names.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: "discoverable-{{ include "postgres-cnpg.fullname" . }}"
  annotations:
    onyxia/discovery: "postgres"
type: Opaque
data:
  postgres-service: {{ $fullname | b64enc | quote }}
  postgres-password: {{ .Values.auth.postgresPassword | default ".Values.auth.postgresPassword"  | b64enc | quote }}
  password: {{ .Values.auth.password | default ".Values.auth.password"  | b64enc | quote }}
  postgres-username: {{ .Values.auth.username | default ".Values.auth.username"  | b64enc | quote }}
  postgres-database: {{ .Values.auth.database | default ".Values.auth.database" | b64enc | quote }}
  postgres-port: {{ (index .Values.ports 0).port | quote }}
{{- end -}}