windmill: 
  windmill:
    baseDomain: user-inesh-916857-0.user.lab.sspcloud.fr
    workerGroups: 
      - name: "default"
        # -- Controller to use. Valid options are "Deployment" and "StatefulSet"
        controller: "Deployment"
        replicas: 1
        privileged: false
    privileges: false
    databaseUrl: postgres://user-inesh:tyignnhexh0j7pigs4y9@windmill-postgresql/windmill?sslmode=disable
    imagePullPolicy: Always
  ingress:
    enabled: true
    className: "onyxia"
    annotations: {}
    # -- TLS config for the ingress resource. Useful when using cert-manager and nginx-ingress
    tls: []
  postgresql:
    # -- enabled included Postgres container for demo purposes only using cloudnative-pg
    enabled: true
    resources:
      limits:
        memory: "2Gi"
    auth:
      postgresUser: user-inesh
      postgresPassword: tyignnhexh0j7pigs4y9
      database: windmill
    # -- persistence configuration for PostgreSQL data
    persistence:
      # -- enable persistence using PVC
      enabled: false
      # -- storage class for the PVC (leave empty for default)
      storageClass: ""
      # -- access mode for the PVC
      accessMode: ReadWriteOnce
      # -- size of the PVC
      size: 50Gi
