global:
  suspend: false

imageCatalog:
  name: postgresql-standard-trixie
  major: 18

auth:
  username: changeme
  password: changeme
  database: defaultdb

ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: pgbouncer

storage:
  size: 10Gi

security:
  networkPolicy:
    enabled: false

userPreferences:
  language: en

discovery:
  enabled: false